version: "3.7"
services:
  nginx:
    image: nginx:alpine
    container_name: book-store-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - bookstore
    depends_on:
     - book-store

  book-store:
    build:
      args:
        user: laravel
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: book-store
    container_name: book-store
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      - "SERVICE_NAME=backend"
      - "DB_PORT=3306"
      - "DB_HOST=book-store-db"
      - "DB_DATABASE=book-store"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
    depends_on:
      - db
    networks: 
      - bookstore
      
  db:
    image: mariadb
    container_name: book-store-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - bookstore

networks:
  bookstore:
    driver: bridge